export const CATEGORY_REQUESTING_LIST = 'CATEGORY_REQUEST_LIST'
export const CATEGORY_REQUEST_LIST_DONE = 'CATEGORY_REQUEST_LIST_DONE'
export const CATEGORY_REQUEST_LIST_FAILED = 'CATEGORY_REQUEST_LIST_FAILED'

export const CATEGORY_REMOVING = 'CATEGORY_REMOVING'
export const CATEGORY_REMOVING_DONE = 'CATEGORY_REMOVING_DONE'
export const CATEGORY_REMOVING_FAILED = 'CATEGORY_REMOVING_FAILED'

export const CATEGORY_UPDATING = 'CATEGORY_UPDATING'
export const CATEGORY_UPDATING_DONE = 'CATEGORY_UPDATING_DONE'
export const CATEGORY_UPDATING_FAILED = 'CATEGORY_UPDATING_FAILED'

export const CATEGORY_CREATING = 'CATEGORY_CREATING'
export const CATEGORY_CREATING_DONE = 'CATEGORY_CREATING_DONE'
export const CATEGORY_CREATING_FAILED = 'CATEGORY_CREATING_FAILED'

export const CATEGORY_REQUESTING_VIEW = 'CATEGORY_REQUESTING_VIEW'
export const CATEGORY_REQUESTING_VIEW_DONE = 'CATEGORY_REQUESTING_VIEW_DONE'
export const CATEGORY_REQUESTING_VIEW_FAILED = 'CATEGORY_REQUESTING_VIEW_FAILED'

export const CATEGORY_SEARCHING_LIST = 'CATEGORY_SEARCHING_LIST'
export const CATEGORY_SEARCHING_LIST_DONE = 'CATEGORY_SEARCHING_LIST_DONE'
export const CATEGORY_SEARCHING_LIST_FAILED = 'CATEGORY_SEARCHING_LIST_FAILED'
export const SELECT_CATEGORY = 'SELECT_CATEGORY'
