export const LOADING_TAGS = 'LOADING_TAGS';
export const LOAD_TAGS_DONE = 'LOAD_TAGS_DONE';
export const LOAD_TAGS_FAILED = 'LOAD_TAGS_FAILED';
export const REMOVING_TAG = 'REMOVING_TAG';
export const REMOVE_DONE = 'REMOVE_DONE';
export const REMOVE_FAILED = 'REMOVE_FAILED';

export const LOADING_TAG = 'LOADING_TAG';
export const LOAD_TAG_FAILED = 'LOAD_TAG_FAILED';
export const LOAD_TAG_DONE = 'LOAD_TAG_DONE';

export const LOADING_TAG_NOTES = 'LOADING_TAG_NOTES';
export const LOAD_TAG_NOTES_FAILED = 'LOAD_TAG_NOTES_FAILED';
export const LOAD_TAG_NOTES_DONE = 'LOAD_TAG_NOTES_DONE';