export const NOTE_REQUESTING_VIEW = 'NOTE_REQUESTING_VIEW'
export const NOTE_REQUESTING_VIEW_DONE = 'NOTE_REQUESTING_VIEW_DONE'
export const NOTE_REQUESTING_VIEW_FAILED = 'NOTE_REQUESTING_VIEW_FAILED'

export const NOTE_SAVING_VIEW = 'NOTE_SAVING_VIEW'
export const NOTE_SAVING_VIEW_DONE = 'NOTE_SAVING_VIEW_DONE'
export const NOTE_SAVING_VIEW_FAILED = 'NOTE_SAVING_VIEW_FAILED'
