export const NOTE_REQUESTING_VIEW = 'NOTE_REQUESTING_VIEW'
export const NOTE_REQUESTING_VIEW_DONE = 'NOTE_REQUESTING_VIEW_DONE'
export const NOTE_REQUESTING_VIEW_FAILED = 'NOTE_REQUESTING_VIEW_FAILED'

export const NOTE_SAVING_VIEW = 'NOTE_SAVING_VIEW'
export const NOTE_SAVING_VIEW_DONE = 'NOTE_SAVING_VIEW_DONE'
export const NOTE_SAVING_VIEW_FAILED = 'NOTE_SAVING_VIEW_FAILED'
export const NOTE_REMOVING_DONE = 'NOTE_REMOVING_DONE'

export const NOTE_NEW_LOAD_NOTEBOOK = 'NOTE_NEW_LOAD_NOTEBOOK'
export const NOTE_NEW_LOAD_NOTEBOOK_DONE = 'NOTE_NEW_LOAD_NOTEBOOK_DONE'
export const NOTE_NEW_LOAD_NOTEBOOK_FAILED = 'NOTE_NEW_LOAD_NOTEBOOK_FAILED'
